/**
 * The homepage wallpaper: wide diagonal bands carrying a Greek frieze, under a
 * radial vignette that calms the centre so the amphora stays the focal point.
 *
 * The bands and the frieze are separate layers inside one rotated frame, so
 * they share an origin — and therefore stay aligned — while keeping their own
 * opacity.
 *
 * Everything visual is declared in the `.myth-backdrop` block in
 * `app/globals.css` and tuned through the custom properties documented there.
 * The frieze artwork is generated by `scripts/backdrop/build-frieze.js`
 * (`npm run backdrop`).
 */
export default function MythBackdrop({ className = "" }: { className?: string }) {
  return (
    <div className={`myth-backdrop ${className}`.trimEnd()} aria-hidden="true">
      <div className="myth-backdrop__weave">
        <div className="myth-backdrop__bands" />
        <div className="myth-backdrop__frieze" />
      </div>

      <div className="myth-backdrop__vignette" />
    </div>
  );
}
