// Generated by `npm run content:sync` from content/weeks/2026-W34.json.
// Do not edit: the amphora's painted panels are derived from the active week.
//
// Consumed only by scripts/amphora/{build,verify}.js. Application code reads
// content through lib/content instead.

export const vasePanels = {
  prometheus: {
    name: "Prometheus",
    angle: 0,
  },
  medusa: {
    name: "Medusa",
    angle: 120,
  },
  icarus: {
    name: "Icarus",
    angle: 240,
  },
} as const;

export type VasePanel = keyof typeof vasePanels;
